version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PUBLIC_SANITY_PROJECT_ID: "${PUBLIC_SANITY_PROJECT_ID}"
        PUBLIC_SANITY_DATASET: "${PUBLIC_SANITY_DATASET}"
        PUBLIC_PAGE_TITLE: "${PUBLIC_PAGE_TITLE}"
        PUBLIC_NAVBAR_TITLE: "${PUBLIC_NAVBAR_TITLE}"
        PUBLIC_COPYRIGHT_HOLDER: "${PUBLIC_COPYRIGHT_HOLDER}"
        SANITY_STUDIO_STUDIO_HOST: "${SANITY_STUDIO_STUDIO_HOST}"
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      PUBLIC_SANITY_PROJECT_ID: "${PUBLIC_SANITY_PROJECT_ID}"
      PUBLIC_SANITY_DATASET: "${PUBLIC_SANITY_DATASET}"
      PUBLIC_PAGE_TITLE: "${PUBLIC_PAGE_TITLE}"
      PUBLIC_NAVBAR_TITLE: "${PUBLIC_NAVBAR_TITLE}"
      PUBLIC_COPYRIGHT_HOLDER: "${PUBLIC_COPYRIGHT_HOLDER}"
